# Generated by Django 2.2 on 2019-12-09 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yard', models.CharField(default='Auburn', max_length=20)),
                ('lot_num', models.IntegerField(blank=True)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('make', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=20)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('engine', models.CharField(blank=True, max_length=20)),
                ('fuel', models.CharField(default='Gas', max_length=20)),
                ('reg_date', models.DateTimeField(blank=True)),
                ('catagory', models.CharField(default='Cars', max_length=20)),
                ('price', models.IntegerField(default=0.0)),
                ('odom', models.IntegerField(blank=True)),
                ('keys', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('avalible_date', models.DateTimeField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellers.Seller')),
            ],
        ),
    ]
