# Generated by Django 2.2 on 2019-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liensale',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='liensales/'),
        ),
        migrations.AlterField(
            model_name='liensale',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='liensales/'),
        ),
        migrations.AlterField(
            model_name='liensale',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='liensales/'),
        ),
        migrations.AlterField(
            model_name='liensale',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='liensales/'),
        ),
        migrations.AlterField(
            model_name='liensale',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='liensales/'),
        ),
        migrations.AlterField(
            model_name='liensale',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='liensales/'),
        ),
        migrations.AlterField(
            model_name='liensale',
            name='photo_main',
            field=models.ImageField(upload_to='liensales/'),
        ),
    ]
