# Generated by Django 2.2 on 2019-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liens', '0003_liensale_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='liensale',
            name='slug',
            field=models.SlugField(default='abc'),
        ),
    ]
