# Generated by Django 2.2 on 2019-12-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liens', '0004_liensale_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liensale',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
