# Generated by Django 2.2 on 2019-12-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liens', '0005_auto_20191209_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liensale',
            name='seller',
        ),
    ]
