# Generated by Django 2.2 on 2019-12-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liens', '0006_remove_liensale_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liensale',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
