# Generated by Django 2.2 on 2019-12-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('liens', '0007_auto_20191209_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='liensale',
            name='seller',
            field=models.ForeignKey(default='stacey', on_delete=django.db.models.deletion.DO_NOTHING, to='sellers.Seller'),
            preserve_default=False,
        ),
    ]
