# Generated by Django 2.2 on 2019-12-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('liens', '0009_remove_liensale_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='liensale',
            name='seller',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sellers.Seller'),
        ),
    ]
