# Generated by Django 2.2 on 2020-01-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liens', '0011_remove_liensale_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liensale',
            name='avalible_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='liensale',
            name='reg_date',
            field=models.DateField(blank=True),
        ),
    ]
