# Generated by Django 2.2 on 2019-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagesale',
            name='item',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
